# Reference: https://github.com/actions/starter-workflows/blob/main/ci/r.yml
# also derived from https://github.com/r-lib/actions/tree/master/examples

name: CRAN Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  R-CMD-Check:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        r-version: ['4.4.3']
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    
    steps:
      - uses: actions/checkout@v4
        
      - name: install libcurl-devel on linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libcurl4-openssl-dev
        # required for rcmdcheck, see
        # https://github.com/florianhartig/DHARMa/issues/316

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      
      - name: Install remotes and rcmdcheck
        run: |
          install.packages(c('remotes', 'rcmdcheck'))
        shell: Rscript {0}
      
      - name: Install Dependencies 
        run: |
          remotes::install_github('cran/binostics')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        # cran/binostics requires separate installation 
        # because it cannot be found using regular install.packages()
      
      - name: Check R Package Using rcmdcheck
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        
      